scrape_configs:
  - job_name: 'ninedot-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'app_blue:8080', 'app_green:8080' ]
        labels:
          application: ninedot-api
